package utils

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const ProxyMarker = "generated by runx add"

var ErrEnvFileNotFound = errors.New("envfile not found")

type MergedEnvEntry struct {
	Value      string
	LastSource string
	Sources    []string
}

type ResolvedEnvFile struct {
	Name  string
	Path  string
	Found bool
	Trace []string
}

func LoadEnvFiles(paths []string) (map[string]string, error) {
	merged, _, _, err := LoadEnvFilesDetailed(paths)
	if err != nil {
		return nil, err
	}
	return merged, nil
}

func LoadEnvFilesDetailed(paths []string) (map[string]string, []ResolvedEnvFile, map[string]MergedEnvEntry, error) {
	merged := map[string]string{}
	resolvedEnvFiles := []ResolvedEnvFile{}
	entryDetails := map[string]MergedEnvEntry{}

	for _, name := range paths {
		resolved, trace, err := ResolveEnvFilePathDetailed(name)
		if err != nil {
			if errors.Is(err, ErrEnvFileNotFound) {
				resolvedEnvFiles = append(resolvedEnvFiles, ResolvedEnvFile{Name: name, Found: false, Trace: trace})
				continue
			}
			return nil, nil, nil, err
		}
		resolvedEnvFiles = append(resolvedEnvFiles, ResolvedEnvFile{Name: name, Path: resolved, Found: true, Trace: trace})
		if err := mergeEnvFileDetailed(merged, entryDetails, resolved, name); err != nil {
			return nil, nil, nil, err
		}
	}

	return merged, resolvedEnvFiles, entryDetails, nil
}

func NormalizeEnvFileName(name string) (string, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return "", fmt.Errorf("--envfile requires a file name or absolute path")
	}
	if filepath.IsAbs(name) {
		return filepath.Clean(name), nil
	}
	if strings.ContainsAny(name, `/\\`) {
		return "", fmt.Errorf("--envfile accepts file name or absolute path only (relative paths are not allowed): %s", name)
	}
	if name == "." || name == ".." {
		return "", fmt.Errorf("invalid envfile name: %s", name)
	}
	if filepath.Base(name) != name {
		return "", fmt.Errorf("--envfile accepts file name or absolute path only (relative paths are not allowed): %s", name)
	}
	return name, nil
}

func ResolveEnvFilePath(name string) (string, error) {
	path, _, err := ResolveEnvFilePathDetailed(name)
	return path, err
}

func ResolveEnvFilePathDetailed(name string) (string, []string, error) {
	trace := []string{}

	if filepath.IsAbs(name) {
		candidate := filepath.Clean(name)
		trace = append(trace, candidate)
		if info, err := os.Stat(candidate); err == nil {
			if info.IsDir() {
				return "", trace, fmt.Errorf("envfile is a directory: %s", candidate)
			}
			return candidate, trace, nil
		} else if !os.IsNotExist(err) {
			return "", trace, fmt.Errorf("failed to stat envfile %s: %w", candidate, err)
		}
		return "", trace, fmt.Errorf("%w: %s (checked absolute path only)", ErrEnvFileNotFound, candidate)
	}

	cwd, err := os.Getwd()
	if err != nil {
		return "", trace, fmt.Errorf("failed to get current directory: %w", err)
	}

	for {
		candidate := filepath.Join(cwd, name)
		trace = append(trace, candidate)
		if info, err := os.Stat(candidate); err == nil {
			if info.IsDir() {
				return "", trace, fmt.Errorf("envfile is a directory: %s", candidate)
			}
			return candidate, trace, nil
		} else if !os.IsNotExist(err) {
			return "", trace, fmt.Errorf("failed to stat envfile %s: %w", candidate, err)
		}

		parent := filepath.Dir(cwd)
		if parent == cwd {
			break
		}
		cwd = parent
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return "", trace, fmt.Errorf("envfile %s not found up to root and failed to resolve home dir: %w", name, err)
	}
	homeCandidate := filepath.Join(home, name)
	trace = append(trace, homeCandidate)
	if info, err := os.Stat(homeCandidate); err == nil {
		if info.IsDir() {
			return "", trace, fmt.Errorf("envfile is a directory: %s", homeCandidate)
		}
		return homeCandidate, trace, nil
	} else if !os.IsNotExist(err) {
		return "", trace, fmt.Errorf("failed to stat envfile %s: %w", homeCandidate, err)
	}

	return "", trace, fmt.Errorf("%w: %s (searched current dir to root, then home dir)", ErrEnvFileNotFound, name)
}

func mergeEnvFileDetailed(target map[string]string, details map[string]MergedEnvEntry, path string, sourceName string) error {
	f, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("failed to open envfile %s: %w", path, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "export ") {
			line = strings.TrimSpace(strings.TrimPrefix(line, "export "))
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			return fmt.Errorf("invalid line in %s:%d: %s", path, lineNo, line)
		}
		key := strings.TrimSpace(parts[0])
		val := strings.TrimSpace(parts[1])
		if key == "" {
			return fmt.Errorf("empty key in %s:%d", path, lineNo)
		}
		normalizedVal := stripOptionalQuotes(val)
		target[key] = normalizedVal
		if details != nil {
			entry := details[key]
			entry.Value = normalizedVal
			entry.LastSource = sourceName
			entry.Sources = appendUniqueSource(entry.Sources, sourceName)
			details[key] = entry
		}
	}

	if err := scanner.Err(); err != nil {
		return fmt.Errorf("failed reading envfile %s: %w", path, err)
	}

	return nil
}

func appendUniqueSource(sources []string, source string) []string {
	for _, s := range sources {
		if s == source {
			return sources
		}
	}
	return append(sources, source)
}

func SortedMergedEnvKeys(details map[string]MergedEnvEntry) []string {
	keys := make([]string, 0, len(details))
	for k := range details {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func stripOptionalQuotes(s string) string {
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

func MergeWithCurrentEnv(overrides map[string]string) []string {
	base := os.Environ()
	index := map[string]int{}
	for i, kv := range base {
		parts := strings.SplitN(kv, "=", 2)
		index[parts[0]] = i
	}

	for k, v := range overrides {
		entry := k + "=" + v
		if idx, ok := index[k]; ok {
			base[idx] = entry
		} else {
			base = append(base, entry)
		}
	}

	return base
}

func QuoteForSh(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
}

func QuoteForCmd(s string) string {
	escaped := strings.ReplaceAll(s, "\"", "\"\"")
	return "\"" + escaped + "\""
}

func IsManagedProxy(path string) (bool, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	return bytes.Contains(bytes.ToLower(b), []byte(ProxyMarker)), nil
}
